SRC_FILES = ./src/main.cpp ./src/product.tpp ./include/product.hpp ./src/my_vector.tpp ./include/my_vector.hpp ./src/test_function.tpp ./include/test_function.hpp

FLAGS = -std=c++11 -Wall -Wextra

main: $(SRC_FILES)
	g++ $(FLAGS) ./src/main.cpp -o main

clean: 
	rm main
